# Generated by Django 4.1.4 on 2022-12-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
    ]
