# Generated by Django 4.1.4 on 2022-12-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_likequestion_likeanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='like_number',
        ),
    ]
